In [1]:
# -*- coding: big5 -*-
"""
作業目標:
在array中，可以靈活應用索引幫助資料擷取
作業重點:
陣列的索引、切片、以及屬性，皆需要注意使用方式
陣列之中索引式由0開始請同學注意

題目:<br>
1.生成一個等差數列，首數為0，尾數為20，公差為1的數列。<br>
2.呈上題，將以上數列取出偶數。<br>
3.呈1題，將數列取出3的倍數。<br>
"""

import numpy as np
#1.生成一個等差數列，首數為0，尾數為20，公差為1的數列。
a = np.arange(0,20,1)
print(a)

#2.呈上題，將以上數列取出偶數。

a = np.arange(0,20,2)
print(a)

#3.呈1題，將數列取出3的倍數。

a = np.arange(3,20,3)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 0  2  4  6  8 10 12 14 16 18]
[ 3  6  9 12 15 18]
